version: "3"
services:
  customer-db:
    container_name: boar-customer-db
    image: mysql:latest
    ports:
      - 3313:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=BOAR_CUSTOMER_DB
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=1234
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
