-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 18:54:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BOAR_ACCOUNT_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BOAR_ACCOUNT_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BOAR_ACCOUNT_DB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema BOAR_CUSTOMER_DB
-- -----------------------------------------------------
USE `BOAR_ACCOUNT_DB` ;

-- -----------------------------------------------------
-- Table `BOAR_ACCOUNT_DB`.`account_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOAR_ACCOUNT_DB`.`account_client` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(45) NOT NULL,
  `date_created` DATE NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOAR_ACCOUNT_DB`.`account_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOAR_ACCOUNT_DB`.`account_data` (
  `account_id` INT NOT NULL,
  `account_number` VARCHAR(45) NULL,
  `account_typ` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  `balance` VARCHAR(45) NULL,
  `interest` VARCHAR(45) NULL,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_account_data_account_client1`
    FOREIGN KEY (`account_id`)
    REFERENCES `BOAR_ACCOUNT_DB`.`account_client` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `BOAR_ACCOUNT_DB`.`bank_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOAR_ACCOUNT_DB`.`bank_card` (
  `bank_card_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `card_number` VARCHAR(45) NULL DEFAULT NULL,
  `card_verification_code` VARCHAR(45) NULL DEFAULT NULL,
  `PIN` VARCHAR(45) NULL DEFAULT NULL,
  `valid_thru` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`bank_card_id`),
  UNIQUE INDEX `bank_card_id_UNIQUE` (`bank_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_card_account_client1`
    FOREIGN KEY (`account_id`)
    REFERENCES `BOAR_ACCOUNT_DB`.`account_client` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
